---
version: '3.8'
services:
  art_bot:
    image: vitalik136/wearthe_bot_monitoring-art_bot:latest
    build:
      context: Weather_art_bot/.
      dockerfile: Dockerfile
    env_file:
      ./.env
      