---
version: '3.3'
services:
  art_bot:
    image: vitalik136/wearthe_bot_monitoring-art_bot:latest
    build:
      context: Weather_art_bot/.
      dockerfile: Dockerfile
    # env_file:
    #   ./.env
    container_name: wearthe_bot_monitoring-art_bot
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPEN_WEATHER_TOKEN: ${OPEN_WEATHER_TOKEN}