version: '3'
services:
  jenkins:
    image: jenkins_master
    build: 
      context: ./jenkins/
      dockerfile: Dockerfile    
    restart: always
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - back-tier

volumes:
    jenkins_data: {}

networks:
  back-tier:
  